### PR TITLE
1.7.10-0.3 

### PR DESCRIPTION
**Pull request by species9000and1**
Don't be intimidated by the amount of deletions. Most of that is just moving stuff around.

So, here's what I've done so far with this mod's source. I added a few things. I updated the version number, and there's also a new config option. Although since this isn't just a single bugfix and some features are re-implmented, I thought I should make it version 0.3. Take a look and see if these changes work well. They worked for me.

### CODE REVIEW

**Comment by CreativeMD** [comment]
I'm not at home until tomorrow, therefore it will take some more time until i can merge this pull request.
But i think changing LivingAttackEvent to LivingHurtEvent won't work (not sure about it).

There will be some more things to add:
- blood splashes if you hit a monster
- hunger effect (lower saturation)
and maybe some other effects as well.

**Comment by species9000and1** [comment]
I tested the mod before making this pull request, Creative... Exactly what problem do you think will arise from changing LivingAttackEvent to LivingHurtEvent? When I did that it fixed the problem of blood and pain visuals appearing when something attempts to damage you in creative. The whole mod still seemed to work...

**Comment by CreativeMD** [comment]
Nice,
but i to be honest it think the red damage overlay is too much?

**Comment by species9000and1** [comment]
Yeah, it is a bit intrusive, although to fix that you'd have to edit the texture, which I can't exactly do... I tried turning down the alpha a bit. That didn't seem to work...

**Comment by CreativeMD** [comment]
I fixed it, changed new Color(1.0F, 1.0F, 1.0F, 1.0F); to new Color(1.0F, 1.0F, 1.0F, 0.5F);

**Pull request merged**
